import Head from "next/head";
import Link from "next/link";
import classes from './index.module.css';
import styles from './index.module.css'
import { Box } from "@mantine/core";

export default function Home() {
  return (
    <>
      <Head>
        <title>CPH Booking</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className={styles.btnBox}>
        <Link href="/login">
          <button className={classes.button}>Book Lokale</button>
        </Link>
        </div>
      </main>
    </>
  );
}
